name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Setup env"
      uses: JRMurr/direnv-nix-action@v4.1.0
    - run: nix flake check -L
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
